### スカラー

といっても、基本的には単独の値を意味する

In [1]:
a = 1
b = 1.5
c = 1.2e5

### ベクトル(一次テンソル)

スカラを直線状に並べたもの≒一次元配列

$$
    \boldsymbol{a} =
        \left(
            \begin{array}{c}
                1 \\
                2 \\
            \end{array}
        \right)
$$

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([-1.1, 1.8e2, 3.14])

### 行列（二次テンソル）

つってもこれも有名すぎるでしょう。

$$
    \boldsymbol{c} =
        \left(
            \begin{array}{ccc}
                1 & 2 & 3 \\
                4 & 5 & 6 \\
            \end{array}
        \right)
$$

In [2]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

### 多次元テンソル

複数次元のテンソルのことです

In [3]:
d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

テンソルの次元変更を `reshape` で

In [7]:
simple = np.array([i for i in range(24)])
reshaped = simple.reshape(4, 6)
print(reshaped)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [8]:
print(simple.reshape(2, 2, 2, 3))

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


In [9]:
print(simple.reshape(2, 3, 4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


`transpose` でテンソルの軸を変更できる

In [17]:
simple = np.array([
    [1, 2, 3, 4],
    [2, 0, 0, 0],
    [3, 0, 0, 0]
])
print(simple.transpose(0, 1))

[[1 2 3 4]
 [2 0 0 0]
 [3 0 0 0]]


In [18]:

print(simple.transpose(1, 0))

[[1 2 3]
 [2 0 0]
 [3 0 0]
 [4 0 0]]


もうちょい複雑なテンソルの軸変換

In [31]:
simple = np.array([
    [
        [1, 2, 3, 4],
        [2, 0, 0, 0],
        [3, 0, 0, 0]
    ],
    [
        [2, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ]
])

print(simple.transpose(0, 2, 1))

[[[1 2 3]
  [2 0 0]
  [3 0 0]
  [4 0 0]]

 [[2 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [19]:

print(simple.transpose(2, 1, 0))

[[[1 2]
  [2 0]
  [3 0]]

 [[2 0]
  [0 0]
  [0 0]]

 [[3 0]
  [0 0]
  [0 0]]

 [[4 0]
  [0 0]
  [0 0]]]


In [23]:
print(simple.transpose(1, 0, 2))

[[[1 2 3 4]
  [2 0 0 0]]

 [[2 0 0 0]
  [0 0 0 0]]

 [[3 0 0 0]
  [0 0 0 0]]]


In [20]:
print(simple.transpose(1, 2, 0))

[[[1 2]
  [2 0]
  [3 0]
  [4 0]]

 [[2 0]
  [0 0]
  [0 0]
  [0 0]]

 [[3 0]
  [0 0]
  [0 0]
  [0 0]]]


In [22]:
print(simple.transpose(2, 0, 1))

[[[1 2 3]
  [2 0 0]]

 [[2 0 0]
  [0 0 0]]

 [[3 0 0]
  [0 0 0]]

 [[4 0 0]
  [0 0 0]]]


### 行列のスカラ倍

つってもこれは基本過ぎるか…

In [25]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(a * 2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


### アダマール積

行列の各要素の積

In [26]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
print(a * b)

[[ 0  2  6]
 [12 20 30]]


### 行列積

ドット積とかいうやつ。  
高校位の数学で習う行列の掛け算はこんな感じ

In [29]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])
print(a.dot(b))

[[16 22]
 [34 49]]


### 転置行列

つってもこれは馴染みがありすぎるか…

In [30]:
a = np.array([
    [1, 2, 3],
    [6, 7, 8]
])
print(a.T)

[[1 6]
 [2 7]
 [3 8]]
